### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by ablanchet**
Sorry for the second commit and PR, must have been one. I'll read the whole page before pushing a PR next time :smile:

### CODE REVIEW

**Comment by kentcb** [comment]
Thanks @ablanchet !

**Comment by ghuntley** [comment]
@ablanchet come join us in Slack, we will provide you with a better WYSIWYG interface for making these changes. https://github.com/reactiveui/ReactiveUI#slack

**Comment by ablanchet** [comment]
Ok great, I've just sent a mail to @paulcbetts asking him to add me

**Comment by ablanchet** [comment]
@ghuntley any news from this thread ? Thanks :)

**Pull request merged**
